version: "3.7"

services:
  textpresso:
      restart: always
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        PYTHONPATH: "/data/textpresso"
        API_URL: "${API_URL}"
        OKTA_API_AUDIENCE: "${OKTA_API_AUDIENCE}"
        OKTA_DOMAIN: "${OKTA_DOMAIN}"
        OKTA_CLIENT_ID: "${OKTA_CLIENT_ID}"
        OKTA_CLIENT_SECRET: "${OKTA_CLIENT_SECRET}"
        AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
        AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
        PYTHONUNBUFFERED: "${PYTHONUNBUFFERED}"
        TMP_PATH: "${TMP_PATH}"
        DATA_PATH: "${DATA_PATH}"
        LOG_PATH: "${LOG_PATH}"
        LOG_URL: "${LOG_URL}"
        CRONTAB_EMAIL: "${CRONTAB_EMAIL}"
        SENDER_EMAIL: "${SENDER_EMAIL}"
        SENDER_PASSWORD: "${SENDER_PASSWORD}"
        REPLY_TO: "${REPLY_TO}"
      hostname: textpresso
      ports:
        - "80:80"
        - "18080:18080"