#!/usr/bin/env bash
/bin/bash -c 'declare -p' | grep -Ev 'BASHOPTS|BASH_VERSINFO|EUID|PPID|SHELLOPTS|UID' > /container.env
cron
mkdir -p /data/textpresso/textpressoapi_data
mkdir -p /data/textpresso/postgres
# The web app (tpc, run by lighttpd as www-data) opens the Berkeley DB environment in /data/textpresso/db and needs
# write access to its region files (__db.*) even to read. Index builds chmod them 777, but region files created any
# other way (e.g. regenerated by root after the arm migration, SCRUM-6649) are root-only: plain searches still work,
# but sort-by-year reads doc_map.db, fails, and the session returns no results.
chmod -f a+rw /data/textpresso/db/__db.* /data/textpresso/db.bk/__db.* 2>/dev/null || true
ln -s /usr/local/bin/tai.sh /usr/local/bin/convert_text
ln -s /usr/local/bin/03pdf2cas4tai.sh /usr/local/bin/tokenize
ln -s /usr/local/bin/07cas1tocas2.sh /usr/local/bin/annotate
ln -s /usr/local/bin/12index.sh /usr/local/bin/index
/root/initialize.sh -p
createdb "www-data"; zcat /usr/local/textpresso/etc/stopwords.postgres.tar.gz | pg_restore -d "www-data"
/root/initialize.sh -l &
/root/initialize.sh -w
/root/initialize.sh -i
textpressoapi -d /data/textpressoapi_data/tokens.db > /data/textpressoapi_data/api.log