/data/textpresso/obofiles4production/go.obo 6 goslim_generic goslim_agr goslim_plant
/data/textpresso/obofiles4production/po.obo 8
/data/textpresso/obofiles4production/to.obo 8
/data/textpresso/obofiles4production/zmays_genes_20260813.obo 3
